name: infiniteloopers
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.18
  table_calendar: ^3.1.3
  flutter_svg: ^2.0.16

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/media/my_ieu.svg
    - lib/media/slide1.png
    - lib/media/ekofit.png
    - lib/media/İzmir_Ekonomi_Üniversitesi_logo.png